# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Row Euclidean Norms Computed in Parallel with OpenMP
#'
#' Computes the Euclidean (L2) norm of each row of a numeric matrix, with the
#' rows divided across threads by _OpenMP_.
#'
#' @param x A `numeric` matrix.
#'
#' @return
#' A `numeric` vector with one entry per row of `x`, each the square root of
#' the sum of squares of that row.
#'
#' @details
#' The `#pragma omp parallel for` directive splits the outer loop over rows
#' across the available _OpenMP_ threads. The directive is only meaningful when
#' the package is compiled with _OpenMP_ support; without it the loop simply
#' runs serially.
#'
#' Only the input matrix is read and the pre-allocated output vector is written
#' inside the parallel region, and each thread writes a distinct index. No _R_
#' API is touched inside the loop, which is what keeps the routine thread-safe.
#'
#' @examples
#' x = matrix(rnorm(20), nrow = 5)
#' parallel_row_norms(x)
#'
#' @export
parallel_row_norms <- function(x) {
    .Call(`_RcppOpenMP_parallel_row_norms`, x)
}

